(() => {
  const { $, formatDate }=window.Revisor;
  const V={};
  V.bars=items=>items.map(([l,v,max=100])=>`<div style="margin:14px 0"><div style="display:flex;justify-content:space-between;font-size:12px"><strong>${l}</strong><span class="muted">${v}</span></div><div class="progress" style="margin-top:6px"><span style="width:${Math.min(100,v/max*100)}%"></span></div></div>`).join('');
  V.dashboard=(models,students,reviews,alerts)=>{const c=reviews.filter(r=>r.status==='Completa'),avg=c.reduce((s,r)=>s+(r.score||0),0)/Math.max(1,c.length),active=models.filter(m=>m.state==='Activa').length,m=[['Revisiones totales',reviews.length,'Historial registrado'],['Promedio académico',avg.toFixed(1),'Sobre 100'],['IA activas',`${active}/${models.length}`,'Catálogo configurable'],['Incompletas',reviews.filter(r=>r.status==='Incompleta').length,'No consumen intento'],['Alertas críticas',alerts.filter(a=>a.type==='Crítica').length,'Requieren atención'],['Estudiantes',students.length,'Registrados']];$('#dashboard-metrics').innerHTML=m.map(([l,v,s])=>`<div class="card metric metric-accent"><div class="metric-label">${l}</div><div class="metric-value">${v}</div><div class="metric-sub">${s}</div></div>`).join('');const ap=c.filter(r=>r.approved).length;$('#grade-distribution').innerHTML=V.bars([['Aprobados',ap,Math.max(1,c.length)],['No aprobados',c.length-ap,Math.max(1,c.length)]]);$('#error-frequency').innerHTML=V.bars([['Metodología',18,20],['Referencias',14,20],['Formato institucional',12,20],['Discusión',9,20],['Conclusiones',7,20]]);$('#recent-reviews').innerHTML=reviews.slice(0,5).map(r=>`<tr><td><strong>${r.student}</strong><div class="small muted">${r.file}</div></td><td>${r.cedula}</td><td>${formatDate(r.date)}</td><td>${r.score??'—'}</td><td>${r.plagiarism!=null?r.plagiarism+'%':'—'}</td><td>${r.ai!=null?r.ai+'%':'—'}</td><td><span class="badge ${r.status==='Completa'?'badge-success':'badge-warning'}">${r.status}</span></td></tr>`).join('');};
  V.models=(models,q='',st='')=>{
    const stateClass=s=>s==='Operativa'?'badge-success':s==='Degradada'||s==='En espera'?'badge-warning':s==='Error de configuración'?'badge-danger':'badge-neutral';
    $('#models-table').innerHTML=models
      .filter(m=>(!q||`${m.name} ${m.provider} ${m.model} ${m.reviewType||''} ${m.level||''} ${m.operationalState||''}`.toLowerCase().includes(q.toLowerCase()))&&(!st||m.state===st))
      .sort((a,b)=>a.priority-b.priority)
      .map(m=>{
        const rate=m.successRate==null?'—':m.successRate+'%';
        const latency=m.averageLatencyMs?((m.averageLatencyMs/1000).toFixed(1)+' s'):'—';
        const last=m.lastReviewStatus||'Sin revisión';
        return `<tr class="model-row">
          <td><strong>${m.name}</strong><div class="small muted">${m.provider}${m.model?` · ${m.model}`:''}</div><div class="small muted">${m.level||''}${m.stableBackup?' · Respaldo estable':''}</div></td>
          <td><span class="priority-pill">#${m.priority}</span></td>
          <td>${m.reviewType||'General'}</td>
          <td><button class="badge ${m.state==='Activa'?'badge-success':'badge-neutral'}" data-toggle-model="${m.id}" style="border:0"><span class="dot"></span>${m.state}</button></td>
          <td><span class="badge ${stateClass(m.operationalState)}">${m.operationalState||'—'}</span></td>
          <td><span class="small ${m.lastTest==='Correcta'?'text-success':m.lastTest==='Error'?'text-danger':'muted'}">${m.lastTest||'Sin probar'}</span></td>
          <td><span class="small ${last==='Correcta'?'text-success':last==='Error'?'text-danger':'muted'}">${last}</span></td>
          <td><strong>${rate}</strong><div class="small muted">${latency}</div></td>
          <td class="nowrap"><button class="btn btn-outline btn-sm" data-test-model="${m.id}">Probar</button> <button class="btn btn-ghost btn-sm" data-edit-model="${m.id}">Editar</button></td>
        </tr>`;
      }).join('');
  };
  V.students=(students,q='')=>{$('#students-table').innerHTML=students.filter(s=>!q||`${s.name} ${s.cedula} ${s.career}`.toLowerCase().includes(q.toLowerCase())).map(s=>`<tr><td><strong>${s.name}</strong></td><td>${s.cedula}</td><td>${s.career}</td><td>${s.used}</td><td><strong>${s.available}</strong></td><td>${s.last?formatDate(s.last):'Sin revisiones'}</td><td><span class="badge badge-success">${s.state}</span></td><td><button class="btn btn-outline btn-sm" data-manage-student="${s.id}">Gestionar</button></td></tr>`).join('');};
  V.reviews=(reviews,q='',st='')=>{$('#reviews-table').innerHTML=reviews.filter(r=>(!q||`${r.student} ${r.file} ${r.cedula}`.toLowerCase().includes(q.toLowerCase()))&&(!st||r.status===st)).map(r=>`<tr><td><strong>${r.student}</strong><div class="small muted">${r.file}</div></td><td>#${r.n}</td><td>${formatDate(r.date)}</td><td>${r.score??'—'}</td><td>${r.plagiarism!=null?r.plagiarism+'%':'—'}</td><td>${r.ai!=null?r.ai+'%':'—'}</td><td>${r.reviewers}</td><td><span class="badge ${r.status==='Completa'?'badge-success':'badge-warning'}">${r.status}</span></td><td><button class="btn btn-outline btn-sm" data-view-review="${r.id}">Ver</button></td></tr>`).join('');};
  V.stats=(models,reviews)=>{const c=reviews.filter(r=>r.status==='Completa'),cards=[['Aprobación',`${Math.round(100*c.filter(r=>r.approved).length/Math.max(1,c.length))}%`],['Similitud media',`${Math.round(c.reduce((s,r)=>s+(r.plagiarism||0),0)/Math.max(1,c.length))}%`],['Posible IA media',`${Math.round(c.reduce((s,r)=>s+(r.ai||0),0)/Math.max(1,c.length))}%`],['Tiempo medio','2m 18s']];$('#stats-cards').innerHTML=cards.map(([l,v])=>`<div class="card metric"><div class="metric-label">${l}</div><div class="metric-value">${v}</div></div>`).join('');$('#stats-errors').innerHTML=V.bars([['Metodología',18,20],['Referencias',14,20],['Formato',12,20],['Resultados',10,20],['Redacción',6,20]]);$('#model-performance').innerHTML=models.filter(m=>m.state==='Activa').sort((a,b)=>(b.successRate??-1)-(a.successRate??-1)).slice(0,8).map(m=>`<tr><td>${m.name}</td><td>${m.successRate==null?'—':m.successRate+'%'}</td><td>${m.averageLatencyMs?((m.averageLatencyMs/1000).toFixed(1)+'s'):'—'}</td></tr>`).join('');};
  V.alerts=alerts=>{$('#alerts-table').innerHTML=alerts.map(a=>`<tr><td><span class="badge ${a.type==='Crítica'?'badge-danger':'badge-warning'}">${a.type}</span></td><td>${a.student}</td><td>${formatDate(a.date)}</td><td>${a.detail}</td><td>${a.state}</td></tr>`).join('');};
  window.AdminView=V;
})();