(() => {
  const { $, $$, api, toast, modal, config }=window.Revisor,V=window.AdminView,seed=window.ADMIN_DEMO_DATA;
  let models=JSON.parse(localStorage.getItem('revisor_models')||'null')||seed.models,students=structuredClone(seed.students),reviews=structuredClone(seed.reviews),alerts=structuredClone(seed.alerts),demo=false;
  const save=()=>localStorage.setItem('revisor_models',JSON.stringify(models));
  const render=()=>{V.dashboard(models,students,reviews,alerts);V.models(models,$('#model-search')?.value||'',$('#model-status')?.value||'');V.students(students,$('#student-search')?.value||'');V.reviews(reviews,$('#review-search')?.value||'',$('#review-status')?.value||'');V.stats(models,reviews);V.alerts(alerts);};
  const showApp=(d=false)=>{demo=d;$('#login-view').classList.add('hidden');$('#app-view').classList.remove('hidden');$('#demo-badge').classList.toggle('hidden',!d);render();};
  $('#admin-login').addEventListener('submit',async e=>{e.preventDefault();$('#admin-login-msg').textContent='Validando credenciales…';try{const d=await api('/auth/admin',{method:'POST',body:JSON.stringify({usuario:$('#admin-user').value.trim(),pin:$('#admin-pin').value.trim()})});sessionStorage.setItem('revisor_token',d.token||'');showApp();}catch(err){if(err.message==='BACKEND_NOT_CONFIGURED'){ $('#admin-login-msg').textContent='El backend seguro todavía no está configurado. Usa el modo demostración para revisar la interfaz.';$('#admin-demo').classList.remove('hidden');}else $('#admin-login-msg').textContent='Credenciales inválidas o servicio no disponible.';}});
  $('#admin-demo').addEventListener('click',()=>showApp(true));$('#logout').addEventListener('click',()=>location.reload());if(config.DEMO_MODE)$('#admin-demo').classList.remove('hidden');
  const nav=n=>{$$('.section').forEach(s=>s.classList.remove('active'));$(`#section-${n}`)?.classList.add('active');$$('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===n));$('.top-nav')?.classList.remove('open');history.replaceState?.(null,'',`#${n}`);};
  document.addEventListener('click',e=>{const n=e.target.closest('[data-nav]');if(n){e.preventDefault();nav(n.dataset.nav);}});
  const set=(id,v)=>$(id).value=v??'';
  function openModel(m=null){$('#model-modal-title').textContent=m?'Editar IA':'Agregar IA';set('#model-id',m?.id);set('#model-name',m?.name);set('#model-provider',m?.provider);set('#model-model',m?.model);set('#model-endpoint',m?.endpoint);set('#model-key','');set('#model-priority',m?.priority||models.length+1);set('#model-weight',m?.weight??1);set('#model-state',m?.state||'Activa');set('#model-specialty',m?.specialty);set('#model-timeout',m?.timeout||90);set('#model-temperature',m?.temperature??.2);set('#model-tokens',m?.tokens||6000);set('#model-review-type',m?.reviewType||'General');set('#model-prompt',m?.prompt);modal('model-modal');}
  $('#model-form').addEventListener('submit',async e=>{e.preventDefault();const id=$('#model-id').value||`model-${Date.now()}`,old=models.find(m=>m.id===id),m={...(old||{}),id,name:$('#model-name').value.trim(),provider:$('#model-provider').value.trim(),model:$('#model-model').value.trim(),endpoint:$('#model-endpoint').value.trim(),priority:+$('#model-priority').value,weight:+$('#model-weight').value,state:$('#model-state').value,specialty:$('#model-specialty').value.trim(),timeout:+$('#model-timeout').value,temperature:+$('#model-temperature').value,tokens:+$('#model-tokens').value,reviewType:$('#model-review-type').value,prompt:$('#model-prompt').value,lastTest:old?.lastTest||'Sin probar'};if(demo){old?Object.assign(old,m):models.push(m);save();render();modal('model-modal',false);toast('IA guardada en modo demostración.','success');}else try{await api(old?`/admin/models/${id}`:'/admin/models',{method:old?'PUT':'POST',body:JSON.stringify({...m,apiKey:$('#model-key').value||undefined})});modal('model-modal',false);toast('IA guardada.','success');}catch{toast('No fue posible guardar la IA.','danger');}});
  async function testModel(id){const m=models.find(x=>x.id===id);if(!m)return;modal('test-modal');$('#test-result').innerHTML=`<div class="alert alert-info"><strong>Probando ${m.name}…</strong></div>`;if(demo){await new Promise(r=>setTimeout(r,700));m.lastTest='Correcta';save();render();$('#test-result').innerHTML=`<div class="alert alert-success"><strong>IA operativa</strong></div><div class="grid grid-3"><div class="card metric"><div class="metric-label">Tiempo</div><div class="metric-value">1.8s</div></div><div class="card metric"><div class="metric-label">Tokens</div><div class="metric-value">428</div></div><div class="card metric"><div class="metric-label">Estado</div><div class="metric-value text-success">OK</div></div></div><div class="card"><h3>Mini revisión</h3><p>Se detectó una afirmación metodológica que debería explicitar población, instrumento y procedimiento.</p></div>`;}else try{const d=await api(`/admin/models/${id}/test`,{method:'POST'});$('#test-result').innerHTML=`<div class="alert alert-success"><strong>IA operativa</strong></div><pre>${JSON.stringify(d,null,2)}</pre>`;}catch(err){$('#test-result').innerHTML=`<div class="alert alert-danger"><strong>Error de prueba</strong><div class="small">${err.message}</div></div>`;}}
  function manageStudent(id){const s=students.find(x=>x.id===id);if(!s)return;$('#student-modal-body').innerHTML=`<div class="grid grid-2"><div class="card metric"><div class="metric-label">Usadas</div><div class="metric-value">${s.used}</div></div><div class="card metric"><div class="metric-label">Disponibles</div><div class="metric-value">${s.available}</div></div></div><h3 style="margin-top:20px">${s.name}</h3><p class="muted">${s.cedula} · ${s.career}</p><div class="toolbar"><button class="btn btn-primary" data-add-attempt="${id}">+ Agregar revisión</button><button class="btn btn-outline" data-restore-attempt="${id}">Restaurar intento</button></div><div class="small muted">Restaurar un intento no elimina el historial.</div>`;modal('student-modal');}
  function viewReview(id){const r=reviews.find(x=>x.id===id);if(!r)return;$('#review-modal-body').innerHTML=`<div class="grid grid-3"><div class="card"><div class="score-big">${r.score??'—'}</div><div class="score-caption">Nota académica / 100</div></div><div class="card metric"><div class="metric-label">Similitud</div><div class="metric-value">${r.plagiarism!=null?r.plagiarism+'%':'—'}</div></div><div class="card metric"><div class="metric-label">Posible IA</div><div class="metric-value">${r.ai!=null?r.ai+'%':'—'}</div></div></div><div style="margin-top:18px" class="alert ${r.status==='Completa'?'alert-success':'alert-warning'}"><div><strong>${r.status}</strong><div class="small muted">${r.reviewers} IA exitosas. ${r.status==='Incompleta'?'El intento no fue descontado.':'Observaciones consolidadas.'}</div></div></div>`;modal('review-modal');}
  document.addEventListener('click',e=>{if(e.target.closest('#add-model-btn'))openModel();const edit=e.target.closest('[data-edit-model]');if(edit)openModel(models.find(m=>m.id===edit.dataset.editModel));const test=e.target.closest('[data-test-model]');if(test)testModel(test.dataset.testModel);const tog=e.target.closest('[data-toggle-model]');if(tog){const m=models.find(x=>x.id===tog.dataset.toggleModel);m.state=m.state==='Activa'?'Inactiva':'Activa';save();render();}const mg=e.target.closest('[data-manage-student]');if(mg)manageStudent(mg.dataset.manageStudent);const add=e.target.closest('[data-add-attempt]');if(add){const s=students.find(x=>x.id===add.dataset.addAttempt);s.available++;render();manageStudent(s.id);toast('Revisión adicional asignada.','success');}const rs=e.target.closest('[data-restore-attempt]');if(rs){const s=students.find(x=>x.id===rs.dataset.restoreAttempt);if(s.used>0)s.used--;s.available++;render();manageStudent(s.id);toast('Intento restaurado.','success');}const vr=e.target.closest('[data-view-review]');if(vr)viewReview(vr.dataset.viewReview);});
  ['model-search','student-search','review-search'].forEach(id=>$('#'+id).addEventListener('input',render));['model-status','review-status'].forEach(id=>$('#'+id).addEventListener('change',render));
  $('#export-summary').addEventListener('click',()=>{const csv=['Estudiante,Cedula,Nota,Plagio,Posible IA,Estado',...reviews.map(r=>`${r.student},${r.cedula},${r.score??''},${r.plagiarism??''},${r.ai??''},${r.status}`)].join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='resumen-revisiones.csv';a.click();URL.revokeObjectURL(a.href);});
  const initial=(location.hash||'#inicio').slice(1);if(['inicio','ias','estudiantes','revisiones','informes','estadisticas','alertas'].includes(initial))nav(initial);
})();
